export const troops = [
  {
    name: 'barbarian',
    img: 'https://th.bing.com/th/id/OIP.ey9Hmh97zIRFbHtErV2NVQHaHa?rs=1&pid=ImgDetMain',
    type: 'ground',
    target: 'any',
    attack: 'melee',
    elixir: 'normal',
    super: 'yes'
  },
  {name: 'archer',
    img: 'https://buy-clash.com/wp-content/uploads/2020/11/Sneaky_Archer_info-391x400.jpg',
    type: 'ground',
    target: 'any',
    attack: 'range',
    elixir: 'normal',
    super: 'yes'
  },
  {name: 'giant',
    img: 'https://buy-clash.com/wp-content/uploads/2020/11/Giant_info.png',
    type: 'ground',
    target: 'defenses',
    attack: 'melee',
    elixir: 'normal',
    super: 'yes'
  },
  {name: 'goblin',
    img: 'https://buy-clash.com/wp-content/uploads/2020/11/Goblin_info-455x400.png',
    type: 'ground',
    target: 'loot',
    attack: 'melee',
    elixir: 'normal',
    super: 'yes'
  },
  {name: 'wall breaker',
    img: 'https://vignette.wikia.nocookie.net/clashofclans/images/7/70/Wall_Breaker_info.png/revision/latest/scale-to-width-down/223?cb=20170927230652',
    type: 'ground',
    target: 'walls',
    attack: 'melee',
    elixir: 'normal',
    super: 'yes'
  },
  {name: 'balloon',
    img: 'https://th.bing.com/th/id/OIP.oEdfcB_w4iGcn4d1NSFmBAHaGP?pid=ImgDet&w=197&h=165&c=7',
    type: 'air',
    target: 'defenses',
    attack: 'melee',
    elixir: 'normal',
    super: 'yes'
  },
  {name: 'wizard',
    img: 'https://static.wikia.nocookie.net/clashofclans/images/1/14/Wizard_info.png/revision/latest/scale-to-width-down/250?cb=20170927230801',
    type: 'ground',
    target: 'any',
    attack: 'ranged',
    elixir: 'normal',
    super: 'yes'
  },
  {name: 'healer',
    img: 'https://static.wikia.nocookie.net/clashofclans/images/c/ca/Healer_info.png/revision/latest/scale-to-width-down/224?cb=20170927230835',
    type: 'air',
    target: 'troop',
    attack: 'ranged',
    elixir: 'normal',
    super: 'no'
  },
  {name: 'dragon',
    img: 'https://static.wikia.nocookie.net/clashofclans/images/2/28/Dragon_info.png/revision/latest/scale-to-width-down/284?cb=20170927230914',
    type: 'air',
    target: 'any',
    attack: 'melee',
    elixir: 'normal',
    super: 'yes'
  },
  {name: 'peaka',
    img: 'https://static.wikia.nocookie.net/clashofclans/images/5/54/P.E.K.K.A_info.png/revision/latest/scale-to-width-down/250?cb=20170927230947',
    type: 'ground',
    target: 'any',
    attack: 'melee',
    elixir: 'normal',
    super: 'no'
  },
  {name: 'baby dragon',
    img: 'https://static.wikia.nocookie.net/clashofclans/images/4/44/Baby_Dragon_info.png/revision/latest/scale-to-width-down/250?cb=20180109183158',
    type: 'air',
    target: 'any',
    attack: 'ranged',
    elixir: 'normal',
    super: 'yes'
  },
  {name: 'miner',
    img: 'https://static.wikia.nocookie.net/clashofclans/images/5/56/Miner_info.png/revision/latest/scale-to-width-down/264?cb=20170927231038',
    type: 'ground',
    target: 'any',
    attack: 'melee',
    elixir: 'normal',
    super: 'yes'
  },
  {name: 'electro dragon',
    img: 'https://static.wikia.nocookie.net/clashofclans/images/0/00/Electro_Dragon_info.png/revision/latest/scale-to-width-down/227?cb=20180608130641',
    type: 'air',
    target: 'any',
    attack: 'ranged',
    elixir: 'normal',
    super: 'no'
  },
  {name: 'yeti',
    img: 'https://static.wikia.nocookie.net/clashofclans/images/e/e2/Yeti_info.png/revision/latest/scale-to-width-down/250?cb=20191208082207',
    type: 'ground',
    target: 'defenses',
    attack: 'melee',
    elixir: 'normal',
    super: 'no'
  },
  {name: 'dragon rider',
    img: 'https://static.wikia.nocookie.net/clashofclans/images/e/e0/Dragon_Rider_info.png/revision/latest/scale-to-width-down/450?cb=20210614072354',
    type: 'air',
    target: 'defenses',
    attack: 'melee',
    elixir: 'normal',
    super: 'no'
  },
  {name: 'electro titan',
    img: '',
    type: 'ground',
    target: 'any',
    attack: 'ranged',
    elixir: 'normal',
    super: 'no'
  },
  {name: 'minion',
    img: 'https://static.wikia.nocookie.net/clashofclans/images/a/a4/Minion_info.png/revision/latest/scale-to-width-down/263?cb=20170927231119',
    type: 'air',
    target: 'any',
    attack: 'ranged',
    elixir: 'dark',
    super: 'yes'
  },
  {name: 'hog rider',
    img: 'https://static.wikia.nocookie.net/clashofclans/images/5/54/Hog_Rider_info.png/revision/latest/scale-to-width-down/215?cb=20170927231149',
    type: 'ground',
    target: 'defenses',
    attack: 'melee',
    elixir: 'dark',
    super: 'yes'
  },
  {name: 'valkyrie',
    img: 'https://static.wikia.nocookie.net/clashofclans/images/7/7d/Valkyrie_info.png/revision/latest/scale-to-width-down/219?cb=20170927231228',
    type: 'ground',
    target: 'any',
    attack: 'melee',
    elixir: 'dark',
    super: 'yes'
  },
  {name: 'golem',
    img: 'https://static.wikia.nocookie.net/clashofclans/images/c/c2/Golem_info.png/revision/latest/scale-to-width-down/289?cb=20170927231256',
    type: 'ground',
    target: 'defenses',
    attack: 'melee',
    elixir: 'dark',
    super: 'no'
  },
  {name: 'witch',
    img: 'https://static.wikia.nocookie.net/clashofclans/images/4/4a/Witch_info.png/revision/latest/scale-to-width-down/203?cb=20170927231327',
    type: 'ground',
    target: 'any',
    attack: 'ranged',
    elixir: 'dark',
    super: 'yes'
  },
  {name: 'lava hound',
    img: 'https://static.wikia.nocookie.net/clashofclans/images/0/0a/Lava_Hound_info.png/revision/latest/scale-to-width-down/216?cb=20170927231353',
    type: 'air',
    target: 'air_defense',
    attack: 'melee',
    elixir: 'dark',
    super: 'yes'
  },
  {name: 'bowler',
    img: 'https://static.wikia.nocookie.net/clashofclans/images/d/da/Bowler_info.png/revision/latest/scale-to-width-down/251?cb=20170927231431',
    type: 'ground',
    target: 'ranged',
    attack: 'any',
    elixir: 'dark',
    super: 'yes'
  },
  {name: 'ice golem',
    img: 'https://static.wikia.nocookie.net/clashofclans/images/1/14/Ice_Golem_info.png/revision/latest/scale-to-width-down/350?cb=20181208133316',
    type: 'ground',
    target: 'defenses',
    attack: 'melee',
    elixir: 'dark',
    super: 'no'
  },
  {name: 'headhunter',
    img: 'https://static.wikia.nocookie.net/clashofclans/images/d/dd/Headhunter_info.png/revision/latest/scale-to-width-down/300?cb=20200621142416',
    type: 'ground',
    target: 'heros',
    attack: 'ranged',
    elixir: 'dark',
    super: 'no'
  },
  {name: 'apprentice warden',
    img: 'https://static.wikia.nocookie.net/clashofclans/images/2/27/Apprentice_Warden_info.png/revision/latest/scale-to-width-down/269?cb=20230611151053',
    type: 'ground',
    target: 'troop',
    attack: 'ranged',
    elixir: 'dark',
    super: 'no'
  },

];
