export const troops = [
  {
    name: 'barbarian',
    img: 'https://th.bing.com/th/id/OIP.ey9Hmh97zIRFbHtErV2NVQHaHa?rs=1&pid=ImgDetMain',
    type: 'ground',
    target: 'any',
    attack: 'melee',
    elixir: 'normal',
    super: 'yes'
  },
  {name: 'archer',
    img: 'https://buy-clash.com/wp-content/uploads/2020/11/Sneaky_Archer_info-391x400.jpg',
    type: 'ground',
    target: 'any',
    attack: 'range',
    elixir: 'normal',
    super: 'yes'
  },
  {name: 'giant',
    img: 'https://buy-clash.com/wp-content/uploads/2020/11/Giant_info.png',
    type: 'ground',
    target: 'defenses',
    attack: 'melee',
    elixir: 'normal',
    super: 'yes'
  },
  {name: 'goblin',
    img: 'https://buy-clash.com/wp-content/uploads/2020/11/Goblin_info-455x400.png',
    type: 'ground',
    target: 'loot',
    attack: 'melee',
    elixir: 'normal',
    super: 'yes'
  },
  {name: 'wall breaker',
    img: 'https://vignette.wikia.nocookie.net/clashofclans/images/7/70/Wall_Breaker_info.png/revision/latest/scale-to-width-down/223?cb=20170927230652',
    type: 'ground',
    target: 'walls',
    attack: 'melee',
    elixir: 'normal',
    super: 'yes'
  },
  {name: 'balloon',
    img: 'https://th.bing.com/th/id/OIP.oEdfcB_w4iGcn4d1NSFmBAHaGP?pid=ImgDet&w=197&h=165&c=7',
    type: 'air',
    target: 'defenses',
    attack: 'melee',
    elixir: 'normal',
    super: 'yes'
  },
  {name: 'wizard',
    img: 'https://vignette2.wikia.nocookie.net/clashofclans/images/1/14/Wizard_info.png/revision/latest?cb=20161219220712',
    type: 'ground',
    target: 'any',
    attack: 'ranged',
    elixir: 'normal',
    super: 'yes'
  },
  {name: 'healer',
    img: 'https://www.pngkit.com/png/detail/362-3624065_coc-troops-png.png',
    type: 'air',
    target: 'troop',
    attack: 'ranged',
    elixir: 'normal',
    super: 'no'
  },
  {name: 'dragon',
    img: 'https://i.pinimg.com/736x/6a/84/8d/6a848d3a0726f0bfcdf615718b80ced4.jpg',
    type: 'air',
    target: 'any',
    attack: 'melee',
    elixir: 'normal',
    super: 'yes'
  },
  {name: 'peaka',
    img: 'https://th.bing.com/th/id/R.49a4d1c62e2c91cf3412f1f31cb96197?rik=%2fJP9vuwF7jrGFg&riu=http%3a%2f%2fpm1.narvii.com%2f6348%2f730a64ade5272bab87096008b073198047b5ae78_hq.jpg&ehk=qGyn6M2wSg1Ih6x%2bg5oZp2c%2fAJgYbvYaxxqk0FGqMjw%3d&risl=&pid=ImgRaw&r=0',
    type: 'ground',
    target: 'any',
    attack: 'melee',
    elixir: 'normal',
    super: 'no'
  },
  {name: 'baby dragon',
    img: 'https://wallpapercave.com/wp/wp3889771.png',
    type: 'air',
    target: 'any',
    attack: 'ranged',
    elixir: 'normal',
    super: 'yes'
  },
  {name: 'miner',
    img: 'https://th.bing.com/th/id/OIP.HngOjaTeF1nVJRKzFOxKZAHaHA?rs=1&pid=ImgDetMain',
    type: 'ground',
    target: 'any',
    attack: 'melee',
    elixir: 'normal',
    super: 'yes'
  },
  {name: 'electro dragon',
    img: 'https://th.bing.com/th/id/OIP.90qcvwSziHzN_5ZPxMn4IwHaIK?rs=1&pid=ImgDetMain',
    type: 'air',
    target: 'any',
    attack: 'ranged',
    elixir: 'normal',
    super: 'no'
  },
  {name: 'yeti',
    img: 'https://www.clashchamps.com/wp-content/uploads/2019/10/Yeti_render_002-1536x1536.png',
    type: 'ground',
    target: 'defenses',
    attack: 'melee',
    elixir: 'normal',
    super: 'no'
  },
  {name: 'dragon rider',
    img: 'https://th.bing.com/th/id/OIP.jUI0OrI504tk4EJtVT6pnQHaHa?rs=1&pid=ImgDetMain',
    type: 'air',
    target: 'defenses',
    attack: 'melee',
    elixir: 'normal',
    super: 'no'
  },
  {name: 'electro titan',
    img: 'https://th.bing.com/th/id/OIP.i6IHcFclpP5pM2aCfQycAQHaIS?rs=1&pid=ImgDetMain',
    type: 'ground',
    target: 'any',
    attack: 'ranged',
    elixir: 'normal',
    super: 'no'
  },
  {name: 'minion',
    img: 'https://th.bing.com/th/id/OIP.-iVJVuCcF6rnzY36M94ESgHaDu?rs=1&pid=ImgDetMain',
    type: 'air',
    target: 'any',
    attack: 'ranged',
    elixir: 'dark',
    super: 'yes'
  },
  {name: 'hog rider',
    img: 'https://th.bing.com/th/id/R.6cbb01214a5e2b57e3f03b60f6e6b38b?rik=S9eEO0bOLbU7ZQ&pid=ImgRaw&r=0',
    type: 'ground',
    target: 'defenses',
    attack: 'melee',
    elixir: 'dark',
    super: 'yes'
  },
  {name: 'valkyrie',
    img: 'https://th.bing.com/th/id/R.b1952b453363f34075e08ade0527704f?rik=%2f0RC6GbfQLGtGQ&pid=ImgRaw&r=0',
    type: 'ground',
    target: 'any',
    attack: 'melee',
    elixir: 'dark',
    super: 'yes'
  },
  {name: 'golem',
    img: 'https://th.bing.com/th/id/OIP.C8PIvykYzCY9MsekJPvKIgHaGZ?rs=1&pid=ImgDetMain',
    type: 'ground',
    target: 'defenses',
    attack: 'melee',
    elixir: 'dark',
    super: 'no'
  },
  {name: 'witch',
    img: 'https://th.bing.com/th/id/OIP.TG1gGv3qBsxBqLwdy6NLCAHaJI?rs=1&pid=ImgDetMain',
    type: 'ground',
    target: 'any',
    attack: 'ranged',
    elixir: 'dark',
    super: 'yes'
  },
  {name: 'lava hound',
    img: 'https://th.bing.com/th/id/OIP.hWDOXVhE3cxYlRUtplIL4gAAAA?rs=1&pid=ImgDetMain',
    type: 'air',
    target: 'air_defense',
    attack: 'melee',
    elixir: 'dark',
    super: 'yes'
  },
  {name: 'bowler',
    img: 'https://th.bing.com/th/id/R.6224433181264fd01214a6cc474b02c0?rik=tcMEwYVQlnxbkQ&riu=http%3a%2f%2fvignette3.wikia.nocookie.net%2fclashofclans%2fimages%2fd%2fda%2fBowler_info.png%2frevision%2flatest%3fcb%3d20160321140921&ehk=M8PwTN6xk%2f88aQpIoyx6Mbaxkb%2bTjhnFRm%2fC13vNUpk%3d&risl=&pid=ImgRaw&r=0',
    type: 'ground',
    target: 'ranged',
    attack: 'any',
    elixir: 'dark',
    super: 'yes'
  },
  {name: 'ice golem',
    img: 'https://vignette.wikia.nocookie.net/clashofclans/images/1/14/Ice_Golem_info.png/revision/latest?cb=20181208133316',
    type: 'ground',
    target: 'defenses',
    attack: 'melee',
    elixir: 'dark',
    super: 'no'
  },
  {name: 'headhunter',
    img: 'https://www.clashchamps.com/wp-content/uploads/2020/06/HeadHunter_InfoScreen-1024x1024.png',
    type: 'ground',
    target: 'heros',
    attack: 'ranged',
    elixir: 'dark',
    super: 'no'
  },
  {name: 'apprentice warden',
    img: 'https://th.bing.com/th/id/OIP.6ybC44sTMo33ZrTl0lN3IQAAAA?rs=1&pid=ImgDetMain',
    type: 'ground',
    target: 'troop',
    attack: 'ranged',
    elixir: 'dark',
    super: 'no'
  },

];
